export const Constants = {
    GAMEWORLD_WIDTH: 2016,
    GAMEWORLD_HEIGHT: 1512,
    GAMESCREEN_WIDTH: 840,
    GAMESCREEN_HEIGHT: 380,
    NORMAL_SPEED: 100,
    SPRINT_SPEED: 300,
    STAMINA_X_POS: 220,
    STAMINA_Y_POS: 30,
    STAMINA_WIDTH: 400,
    STAMINA_HEIGHT: 20,
    STAMINA_CONSUME_QTY: 0.0025,
    INIT_ENEMY_NUMBER: 12,
    FISH_ALIVE: 15,
    KILLING_SCORE: 50,
    GET_ITEM_SCORE: 20,
    TIME_PER_MATCH: 120,
    FISH_TEXTURE_KEY: [
        "blueFish",
        "yellowFish",
        "redFish",
        "greenFish",
        "purpleFish"
    ],
    FISH_HEAD_TEXTURE_KEY: [
        "fish1",
        "fish2",
        "fish3",
        "fish4",
        "fish5",
        "fish6",
        "fish7",
        "fish8",
        "fish9",
        "fish10",
        "fish11",
        "fish12",
        "fish13",
        "fish14",
        "fish15"
    ],
    WEAPON_TEXTURE_KEY: [
        "shortSword",
        "longSword",
        "spear1",
        "spear2",
        "katana1",
        "katana2",
        "katana3",
        "blade1",
        "blade2",
        "blade3",
        "flame1",
        "flame2",
        "flame3",
        "ice1",
        "ice2"
    ],
    EVENT_NEW_FISH: "newFish",
    EVENT_FISH_SCORE: "fishScore",
    EVENT_PLAYER_RESPAWN: "respawn",
    EVENT_NEW_ENEMY: "newEnemy",
    EVENT_FISH_KILL_FISH: "fishKillFish",
    STAB_SOUND: "stab",
    GET_STAB_SOUND: "getStab",
    SWALLOW_SOUND: "swallow",
    BUBBLE_SOUND: "bubble",
    FISH_DIE_SOUND: "fishDie",
    START_GAME_SOUND: "startGameMusic",
    GAME_SCENE: "GameScene",
    OVER_SCENE: "OverMenu",
    START_SCENE: "StartScene",
    HUD_SCENE: "HUDScene",
    STATUS_PLAYING: "playing",
    STATUS_WAITING: "waiting",
    STATUS_TIMEOUT: "timeout",
    SMALL_ITEM_VALUE: 0.025,
    BIG_ITEM_VALUE: 0.1,
    NOOB_ENEMY_RATE: 0.2,
    COLLECT_ENEMY_RATE: 0.5,
    CHASING_ENEMY_RATE: 0.9,
    HUNTER_ENEMY_RATE: 1
}
